@echo off
echo Fixing Git configuration...

echo Checking current remotes...
git remote -v

echo Removing incorrect remote...
git remote remove origin

echo Adding correct remote...
git remote add origin https://github.com/Mohamed-Faroug/store_management_system.git

echo Checking remotes again...
git remote -v

echo Pulling latest changes...
git pull origin main --allow-unrelated-histories

echo Adding all files...
git add .

echo Committing changes...
git commit -m "Update: Improved README.md and project structure"

echo Pushing to GitHub...
git push -u origin main

echo Done!
pause
